version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inspirit
    ports:
      - "3307:3306"
    volumes:
      - G:\Developing\Inspirit test task\Data\inspirit.sql